version: "3.9"
services:
  webapp:
    build: ./internal_api
    environment:
      - OPEN_AI_ORG=${OPEN_AI_ORG}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST=webapp_db
      - DB_PORT=5432
      - TOKEN_SECRET=${TOKEN_SECRET}
      - ROOT_PASS=${ROOT_PASS}
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
  
  
  
  webapp_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST=webapp_db
    
    ports:
      - '5432:5432'
    volumes: 
      - new_db:/var/lib/postgresql/data
volumes:
  new_db:
    driver: local